/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import lz77.LZ77;

/**
 *
 * @author USUARIO
 */
public class InterfazArchivos extends javax.swing.JFrame {

    /**
     * Creates new form InterfazArchivos
     */
    public InterfazArchivos() {
        initComponents();
        this.setLocationRelativeTo(null);
        BotonVerArchivoC.setEnabled(false);
        BotonVerArchivoO.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CampoArchivo = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        BotonBuscarArchivo = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        SALIR = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        BotonDesc1 = new javax.swing.JButton();
        BotonVerArchivoC = new javax.swing.JButton();
        BotonVerArchivoO = new javax.swing.JButton();
        BotonComp1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TituloNombreArchivo = new javax.swing.JLabel();
        TituloTxtInicial = new javax.swing.JLabel();
        NombreArchivo = new javax.swing.JLabel();
        ValorTxtInicial = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labeltiempocomprension = new javax.swing.JLabel();
        ValorTxtCom = new javax.swing.JLabel();
        TituloTxtComp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CampoArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(CampoArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 530, 40));

        jLabelTitulo.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabelTitulo.setText("              COMPRENSIÓN DE ARCHIVOS");
        jLabelTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 550, 50));

        BotonBuscarArchivo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        BotonBuscarArchivo.setText("Buscar:");
        BotonBuscarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonBuscarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 90, 40));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 630, 20));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 630, 10));

        SALIR.setBackground(new java.awt.Color(204, 0, 0));
        SALIR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SALIR.setForeground(new java.awt.Color(255, 255, 255));
        SALIR.setText("x");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        getContentPane().add(SALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 40, 30));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 630, 10));

        BotonDesc1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonDesc1.setText("DESCOMPRIMIR ARCHIVO");
        BotonDesc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDesc1ActionPerformed(evt);
            }
        });
        getContentPane().add(BotonDesc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 270, 50));

        BotonVerArchivoC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonVerArchivoC.setText("VER ARCHIVO COMPRIMIDO");
        BotonVerArchivoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVerArchivoCActionPerformed(evt);
            }
        });
        getContentPane().add(BotonVerArchivoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 270, 50));

        BotonVerArchivoO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonVerArchivoO.setText("VER ARCHIVO ORIGINAL");
        BotonVerArchivoO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVerArchivoOActionPerformed(evt);
            }
        });
        getContentPane().add(BotonVerArchivoO, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 270, 50));

        BotonComp1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonComp1.setText("COMPRIMIR ARCHIVO");
        BotonComp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonComp1ActionPerformed(evt);
            }
        });
        getContentPane().add(BotonComp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 270, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Información del Archivo:");

        TituloNombreArchivo.setText("Nombre:");

        TituloTxtInicial.setText("Peso Inicial:");

        NombreArchivo.setText("NULL");

        ValorTxtInicial.setText("NULL");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Tiempo de Comprensión:");

        labeltiempocomprension.setText("NULL");

        ValorTxtCom.setText("NULL");

        TituloTxtComp.setText("Peso Comprimido:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(182, 182, 182)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TituloNombreArchivo)
                            .addComponent(TituloTxtInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ValorTxtInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TituloTxtComp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ValorTxtCom, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labeltiempocomprension, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TituloNombreArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NombreArchivo)
                        .addComponent(labeltiempocomprension)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TituloTxtInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ValorTxtInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TituloTxtComp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ValorTxtCom)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 630, 90));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Archivo a Buscar:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 110, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inner-Wall-Tile-002.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 650, 510));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo4.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonBuscarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarArchivoActionPerformed
        // TODO add your handling code here:
        JFileChooser ventanaBusqueda = new JFileChooser();//Objeto ventana de busqueda
         ventanaBusqueda.setFileSelectionMode(JFileChooser.FILES_ONLY);
         //FileNameExtensionFilter  filter = new FileNameExtensionFilter("Archivo Txt", "txt");
         //ventanaBusqueda.setFileFilter(filter);
         int returnVal = ventanaBusqueda.showOpenDialog(null);//Condicional de aceptacion seleccion
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File archivo = ventanaBusqueda.getSelectedFile();
            CampoArchivo.setText(archivo.getPath());
            this.CampoArchivo.setText(archivo.getAbsolutePath());

           
                File arch = new File(this.CampoArchivo.getText());
                this.NombreArchivo.setText(arch.getName());
                this.ValorTxtInicial.setText("" + arch.length() + " bytes");
        }
    }//GEN-LAST:event_BotonBuscarArchivoActionPerformed

    private void CampoArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoArchivoActionPerformed

    private void BotonVerArchivoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerArchivoCActionPerformed
        // TODO add your handling code here:
        
        if (Desktop.isDesktopSupported()) {
            try {
                if(this.CampoArchivo.getText().contains(".lz77"))
                {
                    File myFile = new File(this.CampoArchivo.getText());
                    Desktop.getDesktop().open(myFile);
                }
                else
                {
                    File myFile = new File(this.CampoArchivo.getText() + ".lz77");
                    Desktop.getDesktop().open(myFile);
                }
                
            } catch (IOException ex) {
                // no application registered for PDFs
            }
         }
    }//GEN-LAST:event_BotonVerArchivoCActionPerformed

    private void BotonComp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonComp1ActionPerformed
        // TODO add your handling code here:}
        long time_start = 0;
        long time_end = 0;
        long timeT = 0;
        LZ77 nuevaCompre = new LZ77();
        try
        {
            if(!CampoArchivo.getText().contains(".lz77"))
                time_start = System.currentTimeMillis();
                nuevaCompre.comprimir(CampoArchivo.getText());
                time_end = System.currentTimeMillis();
                timeT = (time_end - time_start);
                this.labeltiempocomprension.setText("Tiempo: " + String.valueOf(timeT) + " Segundos");
                File arch = new File(this.CampoArchivo.getText()+ ".lz77");
                this.ValorTxtCom.setText("" + arch.length() + " bytes");
                BotonVerArchivoC.setEnabled(true);
        }
        catch(Exception io){
            
        }
        
    }//GEN-LAST:event_BotonComp1ActionPerformed

    private void BotonDesc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDesc1ActionPerformed
        // TODO add your handling code here:
        LZ77 nuevaCompre = new LZ77();
        try
        {
            if(CampoArchivo.getText().contains(".lz77"))
                nuevaCompre.descomprimir(CampoArchivo.getText());
            else
                System.out.println("");
        }
        catch(Exception io){
            
        }
        BotonVerArchivoO.setEnabled(true);
    }//GEN-LAST:event_BotonDesc1ActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SALIRActionPerformed

    private void BotonVerArchivoOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerArchivoOActionPerformed
        // TODO add your handling code here:
        
        if (Desktop.isDesktopSupported()) {
            try {
                File myFile = new File(this.CampoArchivo.getText());
                Desktop.getDesktop().open(myFile);
            } catch (IOException ex) {
                // no application registered for PDFs
            }
         }
    }//GEN-LAST:event_BotonVerArchivoOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazArchivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscarArchivo;
    private javax.swing.JButton BotonComp1;
    private javax.swing.JButton BotonDesc1;
    private javax.swing.JButton BotonVerArchivoC;
    private javax.swing.JButton BotonVerArchivoO;
    private javax.swing.JTextField CampoArchivo;
    private javax.swing.JLabel NombreArchivo;
    private javax.swing.JButton SALIR;
    private javax.swing.JLabel TituloNombreArchivo;
    private javax.swing.JLabel TituloTxtComp;
    private javax.swing.JLabel TituloTxtInicial;
    private javax.swing.JLabel ValorTxtCom;
    private javax.swing.JLabel ValorTxtInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel labeltiempocomprension;
    // End of variables declaration//GEN-END:variables
}
